'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const D=require('../dist/adaptive-director.js'),A=require('../dist/adaptive-audit.js'),{boot,B}=require('./helpers/adaptive-stable-harness.cjs');
const metric=(height=5,holes=0)=>({height,holes,cells:20,bump:0});
function record(d,{height=5,holes=0,added=0,lines=1,ms=2000,input=true,frame=0}={}){
 for(let t=0;t<ms;t+=100)d.tick(Math.min(100,ms-t),true);
 if(frame)d.tick(frame,true);if(input)d.input(true);
 return d.record({now:d.now+ms+frame,before:metric(height,holes),natural:metric(height,holes+added),actual:metric(height,holes+added),lines,hardDrop:true,context:{level:2,gravity:800,baseInterval:38000}});
}
function codes(d){return d.report().diagnostics.waits.map(x=>x.code);}
test('52-window/16-eligible exclusion partition is explicit, not guessed from historical file',()=>{
 const clean={valid:true,reliable:true,assisted:false,inputs:1,ms:2000};const rows=Array.from({length:52},(_,i)=>({...clean,assisted:i>=16}));
 const c=A.counts(rows);assert.equal(c.total,52);assert.equal(c.eligible,16);assert.equal(c.excluded,36);assert.deepEqual(c.primary,{item_relic_window:36});
});
test('overlapping exclusions have one primary count',()=>{
 const c=A.counts([{valid:false,reliable:false,assisted:true,ms:100,inputs:0,auditBadMs:200}]);assert.equal(Object.values(c.primary).reduce((a,b)=>a+b,0),1);assert.equal(Object.values(c.overlap).reduce((a,b)=>a+b,0),4);
});
test('actual record keeps direct frame and after-frame reasons distinct',()=>{const d=new A.AuditDirector();record(d,{frame:200});record(d);const c=d.report().diagnostics.sampleWindow;assert.equal(c.primary.frame_in_placement,1);assert.equal(c.primary.frame_recovery,1);d.evaluate();assert.equal(d.report().diagnostics.sampleWindow.primary.frame_in_placement,1);});
test('risk detected, proposal created and applied times are independent',()=>{
 const d=new A.AuditDirector({mode:'adaptive',style:'calm'});for(let i=0;i<8;i++)record(d,{height:18,lines:0});const p={...d.pending};assert.equal(d.firstRiskAt,8000);assert.equal(p.at,16000);
 d.system('item',metric(18),metric(17),13000);record(d,{height:5,ms:1000}); // last decision can differ from proposal reason
 d.takeInterval(38000,{now:38000});const c=d.report().changes[0];assert.equal(c.detectedAt,8000);assert.equal(c.proposedAt,16000);assert.equal(c.appliedAt,38000);assert.equal(c.waitMs,22000);assert.equal(c.proposalCode,'persistent_risk');assert.match(c.reason,/높은 적재/);
});
test('proposal reason is not overwritten by later item explanation',()=>{
 const d=new A.AuditDirector({mode:'adaptive',style:'calm'});for(let i=0;i<8;i++)record(d,{height:18,lines:0});d.system('item',metric(18),metric(5),13000);for(let i=0;i<6;i++)record(d,{height:5});assert.equal(d.decision.code,'effect');d.takeInterval(38000,{now:38000});const c=d.report().changes[0];assert.equal(c.decisionAtApply,'effect');assert.equal(c.reason,'유효 배치 중 높은 적재 지속');assert.match(c.decisionReasonAtApply,/아이템/);
});
test('pending proposal remains distinct from executed change',()=>{const d=new A.AuditDirector({mode:'adaptive',style:'calm'});for(let i=0;i<8;i++)record(d,{height:18});assert.ok(codes(d).includes('next_cycle'));assert.equal(d.applied,1);assert.equal(d.report().changes.length,0);});
test('cooldown and fresh samples are separately observable',()=>{const d=new A.AuditDirector({mode:'adaptive',style:'calm'});for(let i=0;i<8;i++)record(d,{height:18});d.takeInterval(38000);record(d,{height:18});const c=codes(d);assert.ok(c.includes('cooldown'));assert.ok(c.includes('fresh_samples'));});
test('episode and style limits are separately observable without changing limits',()=>{const d=new A.AuditDirector({mode:'adaptive',style:'challenge'});for(let i=0;i<100;i++){record(d,{height:18});if(d.pending)d.takeInterval(38000);}assert.ok(codes(d).includes('episode_cap'));assert.ok(codes(d).includes('style_bound'));assert.equal(d.proposed,1.15);});
test('frame cancellation logs the matching pending id',()=>{const d=new A.AuditDirector({mode:'adaptive'});for(let i=0;i<40;i++)record(d);const id=d.pending.auditId;d.tick(200,true);assert.equal(d.pending,null);assert.ok(d.report().diagnostics.timeline.some(x=>x.type==='proposal_cancelled'&&x.proposalId===id));});
test('observe records a simulated proposal, never calls it an actual change',()=>{const d=new A.AuditDirector({mode:'observe'});for(let i=0;i<40;i++)record(d);assert.equal(d.takeInterval(38000),38000);const r=d.report();assert.ok(r.diagnostics.timeline.some(x=>x.type==='proposal_simulated'));assert.equal(r.changes[0].actualChanged,false);});
test('off captures no new telemetry events',()=>{const d=new A.AuditDirector({mode:'off'});record(d);d.system('item',metric(),metric(),5000);assert.equal(d.report().diagnostics.timeline.length,0);assert.equal(d.report().placements,0);});
test('read/export snapshots cannot mutate the running director',()=>{const d=new A.AuditDirector();record(d);const r=d.report();r.decision.code='fake';r.diagnostics.timeline[0].type='fake';assert.notEqual(d.report().decision.code,'fake');assert.notEqual(d.report().diagnostics.timeline[0].type,'fake');});
test('timeline is bounded and truncation is visible',()=>{const d=new A.AuditDirector();for(let i=0;i<400;i++)d.system('ground',metric(),metric(),i);const r=d.report();assert.equal(r.diagnostics.timeline.length,A.MAX_LOG);assert.equal(r.diagnostics.droppedTimelineEvents,160);});
test('existing profile version and record rules are preserved',()=>{const d=new A.AuditDirector();assert.equal(d.report().version,'adaptive-v1.0');assert.equal(d.report().ruleset,D.RULESET);assert.equal(d.report().diagnosticVersion,A.VERSION);});
for(const mode of Object.keys(D.MODES))for(const style of Object.keys(D.STYLES))test(`differential unchanged policy: ${mode}/${style}`,()=>{
 let n=123;const rand=()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};const core=new D.Director({mode,style}),audited=new A.AuditDirector({mode,style});
 for(let i=0;i<450;i++){
  const op={height:i%90<40?5:i%90<75?18:9,added:i%70>62?2:0,lines:i%5===0?4:rand()<.4?1:0,ms:rand()<.05?100:rand()<.1?9000:2000,input:rand()>.03,frame:rand()<.01?200:0};
  if(i%57===0)for(const d of [core,audited])d.system('item',metric(18),metric(6),d.now);
  for(const d of [core,audited])record(d,op);
  if(i%13===0){const base=i>350?11000:38000;assert.equal(audited.takeInterval(base),core.takeInterval(base));}
  for(const key of ['applied','proposed','episode','lastChange','lastChangeSample','upVotes','validTotal','hardDrops'])assert.equal(audited[key],core[key],key+' '+i);
  assert.deepEqual(audited.decision,core.decision);assert.deepEqual(audited.pending&&[audited.pending.at,audited.pending.factor,audited.pending.direction],core.pending&&[core.pending.at,core.pending.factor,core.pending.direction]);
 }
});
test('normal app direct spawn collision reports the actual path before board reset',()=>{const a=boot();a.q.start();a.step(500);const g=a.q.run;for(let y=0;y<2;y++)for(let x=3;x<7;x++)g.board[y][x]={id:++g.serial,type:'I',mask:0};g.active.x=0;g.active.y=10;a.q.action('drop');assert.equal(a.q.state,'over');const r=a.q.adaptive.info();assert.equal(r.diagnostics.terminal.code,'spawn_collision');assert.equal(r.diagnostics.terminal.boardRows.length,20);});
test('normal app direct hold collision is not classified as spawn or ground',()=>{const a=boot();a.q.start();const g=a.q.run;g.active.y=10;g.held={type:'O',size:2,x:4,y:0,cells:[{x:0,y:0,id:++g.serial,type:'O'},{x:1,y:0,id:++g.serial,type:'O'},{x:0,y:1,id:++g.serial,type:'O'},{x:1,y:1,id:++g.serial,type:'O'}]};g.board[0][4]={id:++g.serial,type:'I'};a.q.action('hold');assert.equal(a.q.adaptive.info().diagnostics.terminal.code,'hold_collision');});
test('normal app actual ground overflow carries attempted board separately',()=>{const a=boot();a.q.start();const g=a.q.run;g.board[0][0]={id:++g.serial,type:'I'};a.q.riseGround();const r=a.q.adaptive.info();assert.equal(a.q.state,'over');assert.equal(r.diagnostics.terminal.code,'ground_overflow');assert.equal(r.diagnostics.terminal.groundAttempt.topOut,true);assert.equal(r.diagnostics.terminal.groundAttempt.attemptedRows.length,20);});
test('direct QA finish is unknown rather than an invented player error',()=>{const a=boot();a.q.start();a.q.finish();assert.equal(a.q.adaptive.info().diagnostics.terminal.code,'unknown');});
test('result button opens analysis and returns to same result without restarting',()=>{const a=boot();a.q.start();a.step(1000);a.q.action('drop');a.q.finish();const r=a.q.adaptive.info(),result=a.panel();assert.match(result,/data-adaptive="open"/);a.adaptive('open');assert.match(a.panel(),/지난 판 결과/);assert.match(a.panel(),/다음 판 설정/);assert.doesNotMatch(a.panel(),/현재 예고:/);a.adaptive('return');assert.equal(a.q.state,'over');assert.equal(a.panel(),result);assert.equal(a.q.adaptive.info().id,r.id);});
test('menu reset cannot show next games 180 seconds beneath last result',()=>{const a=boot();a.q.start();a.step(1000);a.q.action('drop');a.q.finish();const r=JSON.stringify(a.q.adaptive.info());a.menu('menu');assert.equal(a.q.desert.nextRise,180000);a.menu('settings');a.adaptive('open');assert.match(a.panel(),/지난 판 결과/);assert.doesNotMatch(a.panel(),/현재 예고:|180초/);assert.equal(JSON.stringify(a.q.adaptive.info()),r);});
test('next settings change leaves last outcome and current rules alone',()=>{const a=boot();a.q.start();a.step(500);a.q.action('drop');a.q.finish();const last=JSON.stringify(a.q.adaptive.info());a.adaptive('mode','adaptive');a.adaptive('style','calm');assert.equal(JSON.stringify(a.q.adaptive.info()),last);a.q.start();assert.equal(a.q.adaptive.info().mode,'adaptive');assert.equal(a.q.adaptive.info().style,'calm');assert.equal(a.q.adaptive.info().applied,1);});
test('active diagnostic shows both scheduled base and actual interval in seconds',()=>{const a=boot();a.q.start();a.q.adaptive.session.intervalHistory.push({at:0,base:38000,actual:39900,factor:1.05});a.q.pause();a.q.adaptive.open();assert.match(a.panel(),/기본 38초 → 실제 39.9초/);assert.match(a.panel(),/현재 예고:/);assert.match(a.panel(),/판정 자료 충족도/);assert.doesNotMatch(a.panel(),/관찰 신뢰도/);});
test('legacy history is visible but exclusion reasons are not retroactively fabricated',()=>{const h={version:D.VERSION,id:'legacy',mode:'adaptive',style:'calm',outcome:'gameover',seconds:834,decision:{code:'risk',confidence:.8,metrics:{placements:52,reliable:16,height:20}},intervalHistory:[{base:17000,actual:20400,factor:1.2}]};const a=boot({initial:{'glassfall-adaptive-v1':JSON.stringify({history:[h],profile:D.newProfile()})}});a.menu('settings');a.adaptive('open');assert.match(a.panel(),/13:54/);assert.match(a.panel(),/미수집|상세 제외 사유가 없습니다/);assert.match(a.panel(),/기본 17초 → 실제 20.4초/);});
for(const type of Object.keys(B.ITEMS))test(`normal integrated ${type} effect still credits only natural rows`,()=>{const a=boot();a.q.start();a.q.itemScenario(type);a.q.resume();const drop=a.q.run.dropDistance()*2;a.q.action('drop');a.step(500);assert.equal(a.q.run.score,drop+(type==='mummy'?0:100));assert.equal(a.q.adaptive.info().practice,true);a.q.draw();});
test('pause and pending clear retain clocks, deadlines and score',()=>{const a=boot();a.q.start();a.q.itemScenario('seal');a.q.resume();a.q.action('drop');a.q.pause();const t=a.q.elapsed,b=JSON.stringify(a.q.run.board);a.step(10000);assert.equal(a.q.elapsed,t);assert.equal(JSON.stringify(a.q.run.board),b);a.q.resume();a.step(500);assert.equal(a.q.run.lines,1);});
test('pointer gestures are operational in the actual normal controller',()=>{const a=boot();a.q.start();const x=a.q.run.active.x;a.gesture(40,100,0,0);assert.equal(a.q.run.active.x,x-1);a.gesture(100,100,80,0);a.gesture(100,180,0,-80);assert.ok(a.q.run.held);a.step(500);a.gesture(100,100,0,90);assert.equal(a.q.adaptive.info().placements,1);});
test('3,000 unchanged block transactions regression',()=>{const r=B.regression(3000);assert.equal(r.cases,3000);assert.deepEqual(r.failures,[]);});

test('ground active collision without top overflow is recorded distinctly',()=>{const a=boot();a.q.start();const g=a.q.run;g.active={type:'O',size:2,x:4,y:0,cells:[{x:0,y:0,id:++g.serial,type:'O'},{x:1,y:0,id:++g.serial,type:'O'},{x:0,y:1,id:++g.serial,type:'O'},{x:1,y:1,id:++g.serial,type:'O'}]};g.board[2][4]={id:++g.serial,type:'I'};assert.ok(B.fits(g.board,g.active));a.q.riseGround();const r=a.q.adaptive.info();assert.equal(a.q.state,'over');assert.equal(r.diagnostics.terminal.code,'ground_active_blocked');assert.equal(r.diagnostics.terminal.groundAttempt.topOut,false);});
test('panel replaces ambiguous risk wording with concrete diagnostic gates',()=>{const a=boot();a.q.start();for(let i=0;i<8;i++)record(a.q.adaptive.session,{height:18});a.q.pause();a.q.adaptive.open();assert.match(a.panel(),/추가 가속 중지|다음 주기/);assert.doesNotMatch(a.panel(),/대기 또는 상한/);});
test('observation confirmation never presents itself as real adaptation',()=>{const a=boot();a.q.start();const d=a.q.adaptive.session;for(let i=0;i<40;i++)record(d);d.takeInterval(38000);a.q.pause();a.q.adaptive.open();assert.match(a.panel(),/검토 확정\(실제 변경 없음\)/);assert.match(a.panel(),/기본 38초 → 실제 38초/);});
