'use strict';
// Real controller + real normal engine. DOM/canvas and scheduling are stand-ins.
// This is not a physical-phone render, input-latency, or sand-physics test.
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const E=require('../dist/engine.js'),R=require('../dist/endless-rules.js'),B=require('../dist/block-items.js');
function boot(){
 let now=0;const nodes=new Map(),store={},timers=new Map();let tid=0;
 const draw=new Proxy({createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),createLinearGradient:()=>({addColorStop(){}})}, {get(t,k){return k in t?t[k]:()=>{};}});
 function node(id=''){if(nodes.has(id))return nodes.get(id);const events={};const n={id,dataset:{},style:{setProperty(){}},classList:{add(){},remove(){},toggle(){}},parentElement:{classList:{add(){},remove(){}}},clientWidth:390,clientHeight:740,offsetHeight:35,width:120,height:100,disabled:false,hidden:false,events,getContext:()=>draw,querySelectorAll:()=>[],addEventListener(t,f){(events[t]||=[]).push(f);},focus(){},getBoundingClientRect:()=>({left:0,top:0,width:270,height:540}),setPointerCapture(){},hasPointerCapture:()=>false,releasePointerCapture(){}};nodes.set(id,n);return n;}
 const actions=['hold','rotate','drop'].map(x=>{const n=node(x);n.dataset.action=x;return n;});
 const doc={body:{dataset:{},classList:{add(){},remove(){},toggle(){}}},documentElement:{style:{setProperty(){}}},getElementById:node,querySelector:node,createElement:()=>node('new'+nodes.size),querySelectorAll:s=>s==='[data-action]'?actions:[],addEventListener(){},hidden:false};
 const env={console,document:doc,location:{search:'?qa=1'},matchMedia:()=>({matches:false}),localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>{store[k]=v;}},navigator:{},performance:{now:()=>now},URLSearchParams,devicePixelRatio:1,requestAnimationFrame(){},getComputedStyle:()=>({paddingLeft:'0',paddingRight:'0',paddingTop:'0',paddingBottom:'0',gap:'6'}),setTimeout:(f,ms)=>{timers.set(++tid,{f,at:now+ms});return tid;},clearTimeout:id=>timers.delete(id),addEventListener(){},crypto:{getRandomValues(a){a.fill(1);}},GlassEngine:E,EndlessRules:R,BlockItems:B,MicroSand:{W:120,H:240}};env.window=env;
 vm.runInNewContext(fs.readFileSync(require.resolve('../dist/endless-app.js'),'utf8'),env,{timeout:3000});
 function menu(a,v){const b={dataset:{menu:a,v:String(v??'')},disabled:false};const e={target:{closest:s=>s==='button[data-menu]'?b:null}};for(const f of node('panel').events.click||[])f(e);}
 function step(ms){for(let t=0;t<ms;t+=100){now+=Math.min(100,ms-t);env.__GLASSFALL_QA__.update(Math.min(100,ms-t));}}
 return {q:env.__GLASSFALL_QA__,nodes,store,menu,step,timers,advance(n){now+=n;}};
}
for(const type of Object.keys(B.ITEMS))test(`actual application ${type} clear has no item points`,()=>{const a=boot();a.q.start();a.q.itemScenario(type);a.q.resume();const drop=a.q.run.dropDistance()*2;a.q.action('drop');assert.equal(a.q.state,'clearing');assert.equal(a.q.run.score,drop);a.step(300);assert.equal(a.q.run.score,drop+(type==='mummy'?0:100));assert.equal(a.q.run.lines,type==='mummy'?0:1);assert.equal(a.q.items.practice,true);a.q.draw();});
test('pause freezes item deadline and pending board transaction',()=>{const a=boot();a.q.start();a.q.itemScenario('seal');a.q.resume();a.q.action('drop');a.q.pause();const board=JSON.stringify(a.q.run.board),time=a.q.elapsed;a.step(60000);assert.equal(a.q.elapsed,time);assert.equal(JSON.stringify(a.q.run.board),board);a.q.resume();a.step(500);assert.equal(a.q.run.lines,1);});
test('new game cancels previous item lifecycle and stats',()=>{const a=boot();a.q.start();a.q.itemScenario('sunburst');a.q.resume();a.q.action('drop');a.q.start();a.step(500);assert.equal(a.q.run.score,0);assert.equal(a.q.run.board.flat().filter(Boolean).length,0);assert.equal(a.q.items.stats.spawned,0);assert.equal(a.q.items.purify,0);});
test('NEXT timer is zero even after time jump and normal ticking',()=>{const a=boot();a.q.start();a.q.forceNextItem('seal');a.q.jumpTime(540000);const p=a.q.run.queue[0],s=p.cells.find(c=>c.special).special;a.step(2000);assert.equal(s.deadline,0);assert.equal(s.failed,false);});
test('ITEM OFF removes all six kinds and returns safe normal clears',()=>{const a=boot();a.q.start();a.q.itemScenario('mummy');a.menu('itemtoggle');assert.equal(a.q.items.enabled,false);assert.equal(B.specials(a.q.run.board).length,0);a.q.resume();a.q.action('drop');a.step(500);assert.equal(a.q.run.lines,1);});
test('first ground rise respects warning and three-minute novice schedule',()=>{const a=boot();a.q.start();a.q.jumpTime(177000);assert.equal(a.q.desert.level,0);assert.equal(a.q.desert.nextRise,180000);a.step(2900);assert.equal(a.q.desert.rises,0);a.step(100);assert.equal(a.q.desert.rises,1);assert.equal(a.q.desert.level,1);assert.ok(B.fits(a.q.run.board,a.q.run.active));});
test('ground change is deferred until line transaction is complete',()=>{const a=boot();a.q.start();a.q.itemScenario('oasis');a.q.jumpTime(180000);a.q.desert.nextRise=a.q.elapsed+100;a.q.resume();a.q.action('drop');a.step(300);assert.equal(a.q.desert.rises,0);assert.equal(a.q.run.lines,1);a.step(300);assert.equal(a.q.desert.rises,1);assert.ok(B.fits(a.q.run.board,a.q.run.active));});
test('scarab failure in actual update has safe geometry',()=>{const a=boot();a.q.start();a.q.itemScenario('scarabCurse');a.q.resume();a.step(12000);assert.equal(a.q.items.stats.failed,1);assert.ok(B.fits(a.q.run.board,a.q.run.active));a.q.draw();});
test('retired relic cannot be activated, even with injected inventory',()=>{const a=boot();a.q.start();a.q.desert.inventory.scarab=1;const score=a.q.run.score;assert.equal(a.q.useRelic('scarab'),false);assert.equal(a.q.run.score,score);});
test('development intervention is excluded from saved bests',()=>{const a=boot();a.q.start();a.q.itemScenario('oasis');a.q.run.score=999999;a.q.finish();const stored=JSON.parse(a.store['glassfall-v1']||'{}');assert.ok(!stored.endlessV1);assert.ok(!stored.desertSurvival);});
test('earned reward is retained until queue/capacity allows placement',()=>{const a=boot();a.q.start();a.q.jumpTime(180000);a.q.items.purify=2;B.attach(a.q.run.queue[1],'mummy',a.q.items);a.q.maybeSeedNextItem();assert.equal(a.q.items.purify,2);for(const c of a.q.run.queue[1].cells)delete c.special;a.q.maybeSeedNextItem();assert.equal(a.q.items.purify,0);assert.equal(a.q.run.queue[1].cells.find(c=>c.special).special.type,'oasis');});
test('DEV nested navigation resumes to a valid play state',()=>{const a=boot();a.q.start();a.q.pause();a.q.devPanel();a.menu('devsim');a.menu('back');a.menu('devrelicview');a.menu('back');a.menu('back');assert.equal(a.q.state,'playing');});
test('all developer presets retain valid active geometry',()=>{const a=boot();a.q.start();for(const p of ['high','holes','left','right','ceiling','rise','max']){a.q.loadPreset(p);assert.ok(B.fits(a.q.run.board,a.q.run.active),p);a.q.draw();}});
