'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const B=require('../dist/block-items.js'),R=require('../dist/endless-rules.js');
function game(){const g=new R.NormalGame('test');g.board=B.blank();g.active=null;g.held=null;g.queue=[];return g;}
const put=(g,x,y)=>g.board[y][x]={id:++g.serial,type:'I',mask:0};
function special(g,s,x,y,t){const c=g.board[y][x]||put(g,x,y);B.attach({cells:[c]},t,s);return c.special;}
function full(g,y){for(let x=0;x<10;x++)put(g,x,y);}
function apply(g,rows,now=0){const tx=B.resolve(g.board,rows,now);g.board=tx.board;g.awardClear(tx.scoringRows.length);return tx;}
for(const [n,points] of [[1,100],[2,300],[3,500],[4,800]])test(`ordinary ${n}-row score preserved`,()=>{const g=game();for(let y=20-n;y<20;y++)full(g,y);g.resolve(R.linePlan(g.board));assert.equal(g.score,points);assert.equal(g.lines,n);});
test('NOVICE 7 gravity preserved',()=>{const g=game();assert.equal(g.stageSpeed,1.16);assert.equal(g.gravity,920*1.16);assert.equal(g.lockDelay,650);});
test('no retired scoring definitions',()=>{assert.equal(Object.keys(B.ITEMS).length,6);assert.equal(Object.values(B.ITEMS).filter(x=>x.kind==='good').length,3);assert.equal(B.ITEMS.pharaoh,undefined);assert.equal(B.ITEMS.anubis,undefined);});
test('oasis removes extra row without extra score or line credit',()=>{const g=game(),s=B.state('o');full(g,18);special(g,s,4,18,'oasis');put(g,0,19);put(g,1,19);const t=apply(g,[18]);assert.equal(t.flushed,1);assert.equal(t.extraRemoved,2);assert.equal(g.score,100);assert.equal(g.lines,1);assert.equal(g.board.flat().filter(Boolean).length,0);});
test('oasis no target remains bounded',()=>{const g=game(),s=B.state('o');full(g,19);special(g,s,4,19,'oasis');const t=apply(g,[19]);assert.equal(t.flushed,0);assert.equal(t.extraRemoved,0);assert.equal(g.score,100);});
test('sunburst original 3x3 only, no chain activation',()=>{const g=game(),s=B.state('s');full(g,18);special(g,s,4,18,'sunburst');for(const y of [17,19])for(const x of [3,4,5])put(g,x,y);special(g,s,3,17,'oasis');const sentinel=put(g,8,19);const t=apply(g,[18]);assert.equal(t.extraRemoved,6);assert.equal(t.events.length,1);assert.equal(t.flushed,0);assert.equal(g.score,100);assert.ok(g.board.flat().some(c=>c?.id===sentinel.id));});
test('spear affects only column below marker, maximum six',()=>{const g=game(),s=B.state('p');full(g,10);special(g,s,4,10,'spear');for(let y=11;y<20;y++){put(g,4,y);put(g,5,y);}const t=apply(g,[10]);assert.equal(t.extraRemoved,6);assert.equal(g.board.filter(r=>r[4]).length,3);assert.equal(g.board.filter(r=>r[5]).length,9);assert.equal(g.score,100);});
test('mummy needs two line completions, with no artificial reinsertion',()=>{const g=game(),s=B.state('m');full(g,19);const sp=special(g,s,4,19,'mummy'),id=g.board[19][4].id;const t1=apply(g,[19]);assert.equal(g.score,0);assert.equal(g.lines,0);assert.equal(t1.purified,0);assert.equal(g.board[19][4].id,id);assert.equal(g.board[19][4].special.hp,1);assert.equal(sp.hp,2,'original snapshot not mutated');for(let x=0;x<10;x++)if(x!==4)put(g,x,19);const t2=apply(g,[19]);assert.equal(g.score,100);assert.equal(t2.purified,1);assert.ok(!g.board.flat().some(c=>c?.id===id));});
test('armored multi-row clear credits only removable rows',()=>{const g=game(),s=B.state('multi');full(g,18);full(g,19);special(g,s,3,18,'mummy');const t=apply(g,[18,19]);assert.deepEqual(t.scoringRows,[19]);assert.equal(g.lines,1);assert.equal(g.score,100);assert.equal(g.board[19][3].special.hp,1);});
test('failed or generated curses cannot farm purification',()=>{for(const generated of [true,false]){const g=game(),s=B.state('fail');full(g,19);const sp=special(g,s,4,19,'mummy');sp.hp=1;sp.generated=generated;sp.failed=!generated;assert.equal(apply(g,[19]).purified,0);}});
test('deadline starts only after landing, never NEXT or HOLD',()=>{const g=game(),s=B.state('timer');const p={cells:[{id:++g.serial,type:'I',mask:0}]};B.attach(p,'scarabCurse',s);g.queue=[p];B.arm(g.board,999999);assert.equal(p.cells[0].special.deadline,0);g.held=g.queue.pop();B.arm(g.board,1000000);assert.equal(p.cells[0].special.deadline,0);g.board[19][0]=g.held.cells[0];g.held=null;B.arm(g.board,1000000);assert.equal(g.board[19][0].special.deadline,1012000);B.arm(g.board,1000500);assert.equal(g.board[19][0].special.deadline,1012000);});
test('scarab adds one cell once, leaves score untouched',()=>{const g=game(),s=B.state('bug');special(g,s,4,19,'scarabCurse');B.arm(g.board,0);const first=B.expire(g,s,12000);assert.equal(first[0].blocks,1);assert.equal(g.board.flat().filter(Boolean).length,2);assert.equal(g.score,0);assert.equal(B.expire(g,s,99000).length,0);});
test('scarab cannot overwrite active piece or fill a full line',()=>{const g=game(),s=B.state('protect');special(g,s,4,19,'scarabCurse');g.active={x:3,y:19,cells:[{x:0,y:0},{x:2,y:0},{x:1,y:-1}]};B.arm(g.board,0);const e=B.expire(g,s,12000);assert.equal(e[0].blocks,0);assert.ok(B.fits(g.board,g.active));const g2=game(),s2=B.state('full');for(let x=0;x<10;x++)if(x!==3)put(g2,x,19);special(g2,s2,4,19,'scarabCurse');B.arm(g2.board,0);B.expire(g2,s2,12000);assert.equal(g2.board[19][3],null);});
test('scarab does not create near spawn ceiling',()=>{const g=game(),s=B.state('top');special(g,s,4,2,'scarabCurse');B.arm(g.board,0);assert.equal(B.expire(g,s,12000)[0].blocks,0);});
test('seal petrifies at most two existing cells, no score or added cells',()=>{const g=game(),s=B.state('seal');special(g,s,4,18,'seal');for(const [x,y] of [[3,18],[5,18],[4,19],[4,17]])put(g,x,y);B.arm(g.board,0);const before=g.board.flat().filter(Boolean).length;const e=B.expire(g,s,15000);assert.equal(e[0].blocks,2);assert.equal(g.board.flat().filter(Boolean).length,before);assert.equal(g.score,0);assert.equal(B.liveCount(g),2);assert.equal(B.expire(g,s,999999).length,0);});
test('seal respects queued special capacity',()=>{const g=game(),s=B.state('cap');special(g,s,4,18,'seal');put(g,3,18);put(g,5,18);const p={cells:[{id:++g.serial,type:'I'}]};B.attach(p,'oasis',s);g.queue=[p];B.arm(g.board,0);assert.equal(B.expire(g,s,15000)[0].blocks,1);assert.equal(B.liveCount(g),2);});
test('late clear has no timely purification reward',()=>{const g=game(),s=B.state('late');full(g,19);const sp=special(g,s,4,19,'seal');sp.deadline=1000;assert.equal(apply(g,[19],1001).purified,0);});
test('clear exactly at deadline wins when already locked',()=>{const g=game(),s=B.state('equal');full(g,19);const sp=special(g,s,4,19,'seal');sp.deadline=1000;assert.equal(apply(g,[19],1000).purified,1);});
test('critical board excludes all natural bad picks',()=>{const g=game(),s=B.state('mercy');put(g,0,3);for(let i=0;i<100;i++)assert.equal(B.ITEMS[B.pick(g,s,8)].kind,'good');});
test('two bad streaks force a good pick',()=>{const g=game(),s=B.state('streak');s.badStreak=2;for(let i=0;i<100;i++)assert.equal(B.ITEMS[B.pick(g,s,8)].kind,'good');});
test('LV0 no item, LV1 only oasis',()=>{const g=game(),s=B.state('unlock');assert.equal(B.pick(g,s,0),null);for(let i=0;i<30;i++)assert.equal(B.pick(g,s,1),'oasis');});
test('live count includes active and hold, no extra spawn',()=>{const g=game(),s=B.state('held');g.active={cells:[{}]};g.held={cells:[{}]};B.attach(g.active,'oasis',s);B.attach(g.held,'seal',s);assert.equal(B.liveCount(g),2);assert.equal(B.pick(g,s,8),null);});
test('disabling neutralizes board, active, queue and hold markers',()=>{const g=game(),s=B.state('off');special(g,s,3,17,'mummy');g.active={cells:[{}]};g.held={cells:[{}]};g.queue=[{cells:[{}]}];for(const p of [g.active,g.held,...g.queue])B.attach(p,'seal',s);B.strip(g);assert.equal(B.specials(g.board).length,0);assert.equal(B.liveCount(g),0);});
test('reset prevents old stats/streak/timer leakage',()=>{const s=B.state('reset');s.serial=99;s.purify=3;s.stats.cleared=7;const n=B.state('reset');assert.equal(n.serial,0);assert.equal(n.purify,0);assert.equal(n.stats.cleared,0);});
test('support row removal refuses collision with active piece',()=>{const g=game();put(g,4,10);put(g,1,19);const p={x:4,y:11,cells:[{x:0,y:0}]};assert.equal(B.removeBottom(g.board,p),null);assert.ok(g.board[10][4]);});
test('3,000 randomized actual board transactions',()=>{const r=B.regression(3000);assert.equal(r.cases,3000);assert.deepEqual(r.failures,[]);});
test('inputs are validated',()=>{assert.throws(()=>B.resolve([],[],0),TypeError);assert.throws(()=>game().awardClear(-1),RangeError);});
