'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {boot}=require('./helpers/adaptive-stable-harness.cjs');
function setup(opts={}){
 const a=boot(opts);a.q.start();const moves=[],events=[];
 const move=a.q.run.move.bind(a.q.run);a.q.run.move=(dx,dy=0)=>{const x=a.q.run.active?.x;const ok=move(dx,dy);if(dx)moves.push({at:a.now,dx,ok,x,after:a.q.run.active?.x});return ok;};
 function pointer(type,x=60,y=200,id=1,target='board'){events.push({type,at:a.now});for(const f of a.nodes.get(target).events[type]||[])f({button:0,pointerId:id,clientX:x,clientY:y,detail:1,preventDefault(){}});}
 return Object.assign(a,{pointer,moves,events});
}
for(const [side,x,dir]of[['left',60,-1],['right',220,1]]){
 test(`${side}: 30 taps each move exactly one cell`,()=>{for(let i=0;i<30;i++){const a=setup();const before=a.q.run.active.x;a.pointer('pointerdown',x);a.advance(60);a.pointer('pointerup',x);a.advance(250);assert.equal(a.q.run.active.x,before+dir);assert.equal(a.moves.length,1);}});
 test(`${side}: stationary hold with short ramp; release stops`,()=>{const a=setup();a.pointer('pointerdown',x);a.advance(164);assert.equal(a.moves.length,0);a.advance(1);assert.equal(a.q.drag.state,'REPEATING');a.advance(152);assert.deepEqual(a.moves.map(m=>m.at).slice(0,4),[165,213,255,291]);a.pointer('pointerup',x);a.advance(300);assert.ok(a.moves.length>=4&&a.moves.length<=5);console.log(side,JSON.stringify({down:0,confirmed:165,first:a.moves[0].at,moves:a.moves.map(m=>m.at),up:317}));});
}
test('jitter does not rearm or cancel repeat',()=>{const a=setup();a.pointer('pointerdown');for(let i=0;i<32;i++){a.advance(10);a.pointer('pointermove',60+(i%2?4:-4),203);}assert.deepEqual(a.moves.map(m=>m.at),[165,213,255,291]);});
test('tap/hold boundary has neither dead zone nor duplicate',()=>{for(const age of [1,114,115,150,169,170,171,207]){const a=setup();a.pointer('pointerdown');a.advance(age);a.pointer('pointerup');assert.equal(a.moves.length,1,'age '+age);a.advance(250);assert.equal(a.moves.length,1);}});
test('wall and stack collision never jumps or reverses',()=>{for(const obstacle of [false,true]){const a=setup();if(obstacle){const p=a.q.run.active;for(let y=0;y<20;y++)a.q.run.board[y][p.x-1]={type:'I',id:900+y};}a.pointer('pointerdown');a.advance(650);assert.ok(a.moves.length>=1);for(const m of a.moves)assert.ok(m.after===m.x||m.after===m.x-1);assert.ok(a.moves.some(m=>!m.ok));a.pointer('pointerup');}});
for(const [dx,age]of[[-35,60],[35,60],[-90,300],[90,300]])test(`swipe ${dx}/${age} rotates only and cannot start hold`,()=>{const a=setup();const p=a.q.run.active,old=JSON.stringify(p.cells);a.pointer('pointerdown');a.advance(20);a.pointer('pointermove',60+dx);a.advance(age+400);assert.equal(a.moves.length,0);a.pointer('pointerup',60+dx);assert.notEqual(JSON.stringify(a.q.run.active.cells),old);a.advance(300);assert.equal(a.moves.length,0);});
test('up hold and down harddrop still replace piece without lateral movement',()=>{for(const y of [130,280]){const a=setup();const old=a.q.run.active;a.pointer('pointerdown');a.advance(20);a.pointer('pointermove',60,y);a.advance(60);a.pointer('pointerup',60,y);assert.notEqual(a.q.run.active,old);assert.equal(a.moves.length,0);}});
test('second-finger drop suppresses old finger and followup click',()=>{const a=setup();a.pointer('pointerdown');a.advance(190);a.pointer('pointerdown',0,0,2,'drop');const p=a.q.run.active,x=p.x;a.pointer('click',0,0,2,'drop');a.advance(250);a.pointer('pointermove',100,200);a.pointer('pointerup',100,200);assert.equal(a.q.run.active,p);assert.equal(p.x,x);assert.equal(a.moves.length,1,JSON.stringify(a.moves));});
for(const end of ['pointercancel','lostpointercapture','pause','replace'])test(`repeat cleanup on ${end}`,()=>{const a=setup();a.pointer('pointerdown');a.advance(180);if(end==='pause')a.q.pause();else if(end==='replace')a.q.action('hold');else a.pointer(end);const n=a.moves.length;a.advance(300);assert.equal(a.moves.length,n);});
test('actual crayon particles preserve the same input timing',()=>{const a=setup({FX:'real'});a.fx.trigger(Array.from({length:20},(_,i)=>({col:i%10,row:18+Math.floor(i/10),color:'#f58db8'})),2,2);assert.ok(a.fx.particles.length>0);a.pointer('pointerdown');a.advance(322);assert.deepEqual(a.moves.map(m=>m.at).slice(0,4),[165,213,255,291]);});
test('late timer never performs a catch-up burst',()=>{const a=setup();a.pointer('pointerdown');a.advance(170);const n=a.moves.length;a.advance(200,200);assert.equal(a.moves.length,n+1);});
test('sand stationary hold remains stationary; horizontal drag still moves',()=>{const a=setup();a.q.setKind('sand');a.q.start();const x=a.q.run.active.x;a.pointer('pointerdown');a.advance(300);assert.equal(a.q.run.active.x,x);a.pointer('pointermove',110,200);assert.ok(a.q.run.active.x>x);a.pointer('pointerup',110,200);});
