'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const E=require('../dist/engine.js'),R=require('../dist/endless-rules.js'),M=require('../dist/sand-micro.js');
const crypto=require('node:crypto');
for(const [file,sha]of [['engine.js','9556069dfd3b2cbcbbbf30f4cb542f67dea40aef'],['sand-micro.js','e40947f87561be3c1c36ea0e01ba63a02a265398'],['art.js','f04ed851059569730899be895f66b73880785bad']]){const b=fs.readFileSync('dist/'+file);assert.equal(crypto.createHash('sha1').update('blob '+b.length+'\0').update(b).digest('hex'),sha,'Original '+file+' must remain unchanged');}
const cell=id=>({id,type:'I',mask:15});
function fill(g,n){g.board=E.blank();for(let y=20-n;y<20;y++)for(let x=0;x<10;x++)g.board[y][x]=cell(y*10+x);return R.linePlan(g.board);}
for(const [n,points]of [[1,100],[2,300],[3,500],[4,800]])test(`${n} complete rows score ${points} at level 1`,()=>{const g=new R.NormalGame('test');const r=g.resolve(fill(g,n));assert.equal(r.gain,points);assert.equal(g.lines,n);assert.equal(g.score,points);assert.equal(g.board.flat().filter(Boolean).length,0);});
test('ordinary plan ignores all neighboring crack masks',()=>{const g=new R.NormalGame('normal');fill(g,1);g.board[18][0]=cell(900);g.board[17][0]=cell(901);const p=R.linePlan(g.board);assert.equal(p.cells.length,10);assert.equal(p.extra,0);g.resolve(p);assert.equal(g.board[19][0].id,900);assert.equal(g.board[18][0].id,901);});
test('whole-row collapse retains holes, never compresses columns',()=>{const g=new R.NormalGame('normal');fill(g,1);g.board[10][3]=cell(900);g.resolve(R.linePlan(g.board));assert.equal(g.board[11][3].id,900);assert.equal(g.board[19][3],null);assert.equal(g.board.flat().filter(Boolean).length,1);});
test('non-contiguous cleared rows maintain exact relative row shift',()=>{const board=E.blank();for(const y of [13,19])for(let x=0;x<10;x++)board[y][x]=cell(y*10+x);board[12][0]=cell(900);board[15][1]=cell(901);R.clearRows(board,[13,19]);assert.equal(board[14][0].id,900);assert.equal(board[16][1].id,901);assert.equal(board.flat().filter(Boolean).length,2);});
test('combo increases only on consecutive clearing placements and resets on no-clear',()=>{const g=new R.NormalGame('c');assert.equal(g.resolve(fill(g,1)).gain,100);assert.equal(g.resolve(fill(g,1)).gain,150);assert.equal(g.resolve(fill(g,1)).gain,200);g.noClear();assert.equal(g.resolve(fill(g,1)).gain,100);assert.equal(g.maxCombo,3);});
test('10-line level threshold uses pre-clear level for that clear',()=>{const g=new R.NormalGame('l');g.lines=9;assert.equal(g.level,1);assert.equal(g.resolve(fill(g,2)).gain,300);assert.equal(g.level,2);g.noClear();assert.equal(g.resolve(fill(g,4)).gain,1600);});
test('active, queue, hold and rotated pieces have zero crack masks',()=>{const g=new R.NormalGame('m');for(let n=0;n<40;n++){assert(g.active.cells.every(c=>c.mask===0));g.rotate();assert(g.active.cells.every(c=>c.mask===0));g.hold();assert(g.held.cells.every(c=>c.mask===0));assert(g.queue.every(p=>p.cells.every(c=>c.mask===0)));g.board=E.blank();g.spawn();}});
test('bag sequence is unchanged apart from zeroed crack masks',()=>{const a=new E.Game('same','endless','glass','standard'),b=new R.NormalGame('same');for(let n=0;n<70;n++){assert.equal(a.active.type,b.active.type);a.spawn();b.spawn();}});
test('endless normal starts empty and hold remains once per piece',()=>{const g=new R.NormalGame('h');assert.equal(g.mode,'endless');assert.equal(g.board.flat().filter(Boolean).length,0);assert.equal(g.hold(),true);assert.equal(g.hold(),false);g.spawn();assert.equal(g.hold(),true);});
test('sand still has a 120x240 field and exactly 576 grains per sack',()=>{assert.equal(M.W,120);assert.equal(M.H,240);const r=new M.Run({seed:'a',colors:3,burst:12});assert.equal(r.active.grains.length,576);assert.equal(r.field.cells.length,28800);assert.equal(r.colors,3);assert.equal(r.burst,1728);assert.equal(r.field.count(),0);});
test('sand spawns next sack immediately while deposited grains can still settle',()=>{const r=new M.Run({seed:'a',colors:3,burst:12});const id=r.active.id;r.drop();assert.notEqual(r.active.id,id);assert.equal(r.state,'falling');assert.equal(r.field.count(),576);assert.equal(r.pieces,1);assert(r.field.step()>0);assert.equal(r.field.count(),576);assert.equal(r.moveTo(30),true);});
test('sand mass conserved under multiple drops and natural physics',()=>{const r=new M.Run({seed:'mass',colors:3,burst:12});for(let n=0;n<12&&r.state!=='over';n++){if(r.state==='falling'){r.moveTo([24,60,94][n%3]);r.drop();}for(let i=0;i<100;i++)r.step(1000/60);assert.equal(r.field.count()+r.removed,r.pieces*576);}});
test('sand cannot move through a blocked corner',()=>{const f=new M.Field();f.set(10,10,1);for(const [x,y]of [[10,11],[9,10],[11,10]])f.set(x,y,4);f.step();assert.equal(f.cells[10*120+10],1);});
test('sand burst scoring retains natural chain multipliers',()=>{const r=new M.Run({seed:'score',colors:3,burst:12,gravity:0});for(let y=225;y<240;y++)for(let x=0;x<120;x++)r.field.set(x,y,1);for(let n=0;n<100&&r.removed===0;n++)r.step(50);assert.equal(r.removed,1800);assert.equal(r.score,350);assert.equal(r.maxChain,1);for(let y=225;y<240;y++)for(let x=0;x<120;x++)r.field.set(x,y,2);for(let n=0;n<100&&r.removed===1800;n++)r.step(50);assert.equal(r.removed,3600);assert.equal(r.score,1050);assert.equal(r.maxChain,2);});
test('runtime does not load stage, daily or old controllers',()=>{const html=fs.readFileSync('dist/index.html','utf8');for(const old of ['src="app.js','src="stages.js','src="progression.js','src="sand-route.js','id="sand-board"'])assert(!html.includes(old));const app=fs.readFileSync('dist/endless-app.js','utf8');assert(!app.includes('GlassStages'));assert(!app.includes('finish(\'time\')'));assert(!app.includes('data-stage='));});
test('historical sand URLs route into endless sand, never a stage selection',()=>{const html=fs.readFileSync('dist/sand-micro.html','utf8');assert(html.includes('mode=sand&play=1'));assert(!html.includes('mode=stage'));assert(!html.includes('mode=daily'));});
