'use strict';
const assert=require('node:assert/strict'),M=require('../dist/sand-micro.js'),P=require('../dist/sand-pour.js'),S=require('../dist/stages.js');
let count=0;
function test(name,fn){fn();count++;console.log('PASS',name);}
function settle(r){for(let n=0;n<2000;n++){if(['aiming','over'].includes(r.state))return n;r.step(P.STEP);}throw new Error('settling did not terminate');}
function finishField(f){for(let i=0;i<2000&&f.sleep<4;i++)f.step();assert.ok(f.sleep>=4);}
test('reuses the successful exact Field class',()=>{assert.ok(new P.Run().field instanceof M.Field);});
test('new stock is a dose, not a clump with hidden collision bounds',()=>{const r=new P.Run();assert.equal(r.active.amount,576);assert.equal(r.active.grains,undefined);assert.equal(r.active.bounds,undefined);});
test('same seed gives same old and new color sequence',()=>{const a=new M.Run({seed:'color',colors:3}),b=new P.Run({seed:'color',colors:3});assert.equal(a.active.color,b.active.color);for(let i=0;i<100;i++)assert.equal(a.makePacket().color,b.makeDose().color);});
test('waiting to aim creates no grains and consumes no stock',()=>{const r=new P.Run();for(let i=0;i<1000;i++)r.step(50);assert.equal(r.field.count(),0);assert.equal(r.remaining,576);assert.equal(r.pieces,0);});
test('aiming reaches both edges but never beyond the field',()=>{const r=new P.Run();r.moveTo(-999);assert.equal(r.x,8);r.moveTo(999);assert.equal(r.x,111);assert.equal(r.moveTo(NaN),false);});
test('supply starts gently instead of depositing a solid packet',()=>{const r=new P.Run();r.pour();for(let i=0;i<8;i++)r.step(P.STEP);assert.ok(r.field.count()>0&&r.field.count()<20);assert.equal(r.remaining+r.field.count(),576);});
test('84 ticks supply exactly 576 real grains with mass conserved',()=>{for(const x of [8,60,111]){const r=new P.Run();r.moveTo(x);r.pour();for(let i=0;i<84;i++)r.step(P.STEP);assert.equal(r.delivered,576);assert.equal(r.field.count(),576);assert.equal(r.state,'settling');assert.equal(r.pieces,1);assert.equal(r.remaining,0);settle(r);assert.equal(r.field.count(),576);}});
test('no double pour, movement, or hold during a dose',()=>{const r=new P.Run();r.moveTo(24);r.pour();assert.equal(r.pour(),false);assert.equal(r.moveTo(80),false);assert.equal(r.hold(),false);assert.equal(r.x,24);});
test('hold one time then refreshes after the completed turn',()=>{const r=new P.Run(),id=r.active.id;assert.ok(r.hold());assert.equal(r.held.id,id);assert.equal(r.hold(),false);r.pour();settle(r);assert.ok(r.hold());assert.equal(r.active.id,id);});
test('pause by withholding step preserves field and supply exactly',()=>{const r=new P.Run();r.pour();r.step(50);const a=r.field.cells.slice(),n=r.remaining;assert.deepEqual(r.field.cells,a);assert.equal(r.remaining,n);r.step(0);assert.equal(r.remaining,n);});
test('fixed tick simulation identical at 30, 60 and 120 fps',()=>{const results=[];for(const dt of [1000/30,1000/60,1000/120]){const r=new P.Run({seed:'rate',colors:3});r.pour();for(let i=0;i<400;i++)r.step(dt);settle(r);results.push(r.field.cells.slice());}assert.deepEqual(results[0],results[1]);assert.deepEqual(results[0],results[2]);});
test('no live randomness in settled texture or positions',()=>{const r=new P.Run();r.pour();settle(r);const a=r.field.cells.slice(),s=r.field.shade.slice();for(let i=0;i<100;i++)r.step(50);assert.deepEqual(r.field.cells,a);assert.deepEqual(r.field.shade,s);});
test('real two-chain cascade and existing score formula',()=>{const r=new P.Run({burst:1});r.active=null;r.state='settling';for(let x=0;x<80;x++)r.field.set(x,239,2);for(let x=0;x<120;x++)for(let y=237;y<239;y++)r.field.set(x,y,1);for(let x=0;x<80;x++)r.field.set(x,236,2);settle(r);assert.equal(r.removed,400);assert.equal(r.maxChain,2);assert.equal(r.field.count(),0);assert.equal(r.score,377);});
test('blocked target refuses to start without overwriting any grain',()=>{const r=new P.Run();for(const x of r.columns())r.field.set(x,P.SOURCE_Y,4);const a=r.field.cells.slice();assert.equal(r.pour(),false);assert.deepEqual(r.field.cells,a);r.moveTo(90);assert.ok(r.pour());});
test('fully blocked source band ends the game',()=>{const r=new P.Run();for(let x=0;x<M.W;x++)r.field.set(x,P.SOURCE_Y,4);r.spawn();assert.equal(r.state,'over');assert.ok(r.events.some(e=>e.type==='over'));});
test('inlet jam is bounded; pending grains are not silently discarded',()=>{const r=new P.Run();r.pour();for(const x of r.columns())r.field.set(x,P.SOURCE_Y,4);for(let i=0;i<140;i++)r.step(P.STEP);assert.equal(r.state,'over');assert.equal(r.delivered,0);assert.equal(r.remaining,576);});
test('partial obstruction conserves mass and never replaces a gem',()=>{const r=new P.Run();for(let x=55;x<58;x++)r.field.set(x,P.SOURCE_Y,4);r.pour();settle(r);assert.equal(r.delivered,576);assert.equal(r.field.count(),576);for(let x=55;x<58;x++)assert.equal(r.field.cells[P.SOURCE_Y*M.W+x],4);});
test('very long frame is capped to six physics ticks',()=>{const r=new P.Run();r.pour();r.step(100000);assert.equal(r.stream.ticks,6);assert.ok(r.delivered<50);});
test('all 100 stages retain goal, colors, burst and gem configuration',()=>{for(let stage=1;stage<=100;stage++){const c=S.config(stage,'sand'),r=new P.Run({stage,colors:c.sandColors,burst:c.sandBurst,gems:c.gems});assert.equal(r.colors,stage<=2?2:3);assert.equal(r.burst,c.sandBurst*144);assert.equal(r.field.gems.length,c.gems);assert.ok(c.target>0);}});
test('gem collection still requires neighboring burst',()=>{const f=new M.Field();f.addGem(60,235);assert.equal(f.clear([]).gemCount,0);const indices=[];for(let y=231;y<=239;y++)for(let x=55;x<=65;x++)if(!f.cells[y*120+x]){f.set(x,y,1);indices.push(y*120+x);}assert.equal(f.clear([{color:1,indices}]).gemCount,1);});
test('multiple doses account for every grain even when colors burst',()=>{const r=new P.Run({seed:'many',colors:3});for(let i=0;i<35;i++){r.moveTo([20,60,100][i%3]);r.pour();settle(r);assert.equal(r.field.count()+r.removed,r.delivered);if(r.state==='over')break;}assert.ok(r.pieces>10);});
console.log('\n'+count+' tests passed');
