'use strict';
const assert=require('node:assert/strict'),M=require('../dist/sand-micro.js'),P=require('../dist/sand-flow.js'),S=require('../dist/stages.js');
let count=0;function test(name,fn){fn();count++;console.log('PASS',name);}
function ticks(r,n){for(let i=0;i<n;i++)r.step(P.STEP);}
function settle(r){for(let i=0;i<6000;i++){if(['aiming','over'].includes(r.state))return;ticks(r,1);}throw Error('did not terminate');}
function mass(r){assert.equal(r.field.count()+r.removed,r.delivered);assert.equal(r.delivered+r.remaining,r.accepted*M.PACKET);}
function cascade(r){r.state='settling';for(let x=0;x<80;x++)r.field.set(x,239,2);for(let x=0;x<120;x++)for(let y=237;y<239;y++)r.field.set(x,y,1);for(let x=0;x<80;x++)r.field.set(x,236,2);}
test('Field identity preserved; stock is a dose, not a hidden clump',()=>{const r=new P.Run();assert.ok(r.field instanceof M.Field);assert.equal(r.active.amount,576);assert.equal(r.active.grains,undefined);});
test('next color advances immediately when first supply is accepted',()=>{const r=new P.Run(),next=r.queue[0];assert.ok(r.pour());assert.equal(r.active.id,next.id);assert.equal(r.active.color,next.color);assert.ok(r.ready);assert.equal(r.accepted,1);});
test('can pour a second dose while the first is still being emitted',()=>{const r=new P.Run();r.moveTo(20);r.pour();ticks(r,12);assert.ok(r.delivered>0&&r.delivered<576);r.moveTo(100);assert.ok(r.pour());assert.equal(r.streams.length,2);mass(r);});
test('can pour while all prior grains are still falling to the floor',()=>{const r=new P.Run();r.pour();ticks(r,84);assert.equal(r.state,'settling');assert.equal(r.field.cells.slice(200*120).filter(Boolean).length,0);assert.ok(r.pour());assert.equal(r.accepted,2);});
test('old source and color never follow the next aim position',()=>{const r=new P.Run();r.moveTo(20);r.pour();const s=r.streams[0],color=s.color;r.moveTo(100);r.hold();ticks(r,20);assert.equal(s.x,20);assert.equal(s.color,color);assert.ok(s.columns.every(x=>x>=12&&x<=28));assert.ok(r.field.cells.every((c,i)=>!c||i%120<40));});
test('three sources run simultaneously, every dose completes in 84 free ticks',()=>{const r=new P.Run({burst:1000});for(const x of[20,60,100]){r.moveTo(x);assert.ok(r.pour());}ticks(r,84);assert.equal(r.pieces,3);assert.equal(r.delivered,1728);assert.equal(r.streams.length,0);mass(r);});
test('rapid same-inlet supplies share vacancies fairly without overwrites',()=>{const r=new P.Run({burst:1000});for(let i=0;i<6;i++)assert.ok(r.pour());ticks(r,60);assert.ok(r.streams.every(s=>s.emitted>0));mass(r);settle(r);assert.equal(r.state,'aiming');assert.equal(r.pieces,6);assert.equal(r.delivered,3456);mass(r);});
test('existing physics remainder is not reset by another click',()=>{const r=new P.Run();r.pour();r.step(5);assert.equal(r.accumulator,5);r.pour();assert.equal(r.accumulator,5);r.step(4);assert.equal(r.streams[0].ticks,1);assert.equal(r.streams[1].ticks,1);});
test('hold affects next stock only; one hold per unpoured stock',()=>{const r=new P.Run();r.pour();const s=r.streams[0],c=s.color,id=s.id;assert.ok(r.hold());assert.equal(r.hold(),false);assert.equal(s.color,c);assert.equal(s.id,id);r.moveTo(95);assert.ok(r.pour());assert.ok(r.hold());});
test('same seed consumes identical RNG draws to the clump baseline',()=>{const a=new M.Run({seed:'same',colors:3}),b=new P.Run({seed:'same',colors:3});assert.equal(a.active.color,b.active.color);for(let i=0;i<40;i++)assert.equal(a.makePacket().color,b.makeDose().color);});
test('waiting to aim creates no sand and uses no stock',()=>{const r=new P.Run();ticks(r,500);assert.equal(r.accepted,0);assert.equal(r.field.count(),0);});
test('supply still tapers gently rather than spawning 576 grains at once',()=>{const r=new P.Run();r.pour();ticks(r,8);assert.ok(r.delivered>0&&r.delivered<20);mass(r);});
test('both edge inlets stay within bounds',()=>{for(const x of[-999,999]){const r=new P.Run();r.moveTo(x);assert.ok([8,111].includes(r.x));r.pour();settle(r);assert.equal(r.delivered,576);mass(r);}const r=new P.Run();assert.equal(r.moveTo(NaN),false);});
test('30/60/120 fps converge to identical simultaneous-supply outcomes',()=>{const fields=[];for(const dt of[1000/30,1000/60,1000/120]){const r=new P.Run({seed:'fps',colors:3});for(const x of[20,60,100]){r.moveTo(x);r.pour();}for(let i=0;i<700;i++)r.step(dt);settle(r);mass(r);fields.push(r.field.cells.slice());}assert.deepEqual(fields[0],fields[1]);assert.deepEqual(fields[1],fields[2]);});
test('pause (no step) preserves every stream, field and time remainder',()=>{const r=new P.Run();r.pour();r.moveTo(95);r.pour();r.step(50);const a=r.field.cells.slice(),n=r.remaining,t=r.streams.map(s=>s.ticks);r.step(0);assert.deepEqual(r.field.cells,a);assert.equal(r.remaining,n);assert.deepEqual(r.streams.map(s=>s.ticks),t);});
test('idle terrain positions and shades do not shimmer',()=>{const r=new P.Run();r.pour();settle(r);const a=r.field.cells.slice(),s=r.field.shade.slice(),t=r.field.tick;ticks(r,300);assert.deepEqual(r.field.cells,a);assert.deepEqual(r.field.shade,s);assert.equal(r.field.tick,t);});
test('pending clear keeps exact grain snapshot while input is accepted',()=>{const r=new P.Run({burst:1});cascade(r);for(let i=0;i<1000&&r.state!=='clearing';i++)ticks(r,1);const pending=r.pending,chain=r.chain,a=r.field.cells.slice();assert.ok(pending);r.moveTo(100);assert.ok(r.pour());assert.ok(r.hold());assert.equal(r.state,'clearing');assert.equal(r.pending,pending);assert.equal(r.chain,chain);ticks(r,1);assert.deepEqual(r.field.cells,a);assert.equal(r.streams[0].emitted,0);});
test('accepted clear-time supply resumes after the flash, no lost grains',()=>{const r=new P.Run({burst:1});cascade(r);for(let i=0;i<1000&&r.state!=='clearing';i++)ticks(r,1);r.moveTo(100);r.pour();const p=r.streams[0];ticks(r,50);assert.ok(p.emitted>0);settle(r);assert.equal(r.delivered,576);assert.equal(r.field.count()+r.removed,976);});
test('genuine automatic two-chain and scoring survive unchanged',()=>{const r=new P.Run({burst:1});cascade(r);settle(r);assert.equal(r.removed,400);assert.equal(r.maxChain,2);assert.equal(r.score,377);assert.equal(r.field.count(),0);});
test('new user dose cannot artificially continue an old multiplier',()=>{const r=new P.Run({burst:1});cascade(r);for(let i=0;i<1000&&r.state!=='clearing';i++)ticks(r,1);r.moveTo(100);r.pour();settle(r);const bursts=r.events.filter(e=>e.type==='burst');assert.ok(bursts.length>=2);assert.equal(bursts[0].chain,1);assert.equal(bursts[1].chain,1);});
test('inlet rejection does not consume next color or amount',()=>{const r=new P.Run();for(const x of r.columns())r.field.set(x,P.SOURCE_Y,4);const id=r.active.id;assert.equal(r.pour(),false);assert.equal(r.active.id,id);assert.equal(r.accepted,0);r.moveTo(100);assert.ok(r.pour());});
test('blocked running inlet terminates without inventing or dropping matter',()=>{const r=new P.Run();r.pour();for(const x of r.columns())r.field.set(x,P.SOURCE_Y,4);ticks(r,140);assert.equal(r.state,'over');assert.equal(r.delivered,0);assert.equal(r.remaining,576);assert.equal(r.events.filter(e=>e.type==='over').length,1);mass(r);});
test('small source obstacle is never overwritten',()=>{const r=new P.Run();for(let x=55;x<=57;x++)r.field.set(x,P.SOURCE_Y,4);r.pour();settle(r);assert.equal(r.delivered,576);for(let x=55;x<=57;x++)assert.equal(r.field.cells[P.SOURCE_Y*120+x],4);mass(r);});
test('long frame clamped to six physics ticks',()=>{const r=new P.Run();r.pour();r.step(100000);assert.equal(r.streams[0].ticks,6);});
test('new Run/retry resets pending streams, score and input together',()=>{let r=new P.Run();r.pour();r.pour();ticks(r,50);r=new P.Run();assert.equal(r.streams.length,0);assert.equal(r.remaining,0);assert.equal(r.accepted,0);assert.equal(r.score,0);assert.ok(r.ready);});
test('stage-complete drain accepts no new dose but finishes old supplies',()=>{const r=new P.Run();r.pour();r.moveTo(100);r.pour();r.accepting=false;assert.equal(r.pour(),false);assert.equal(r.hold(),false);settle(r);assert.equal(r.pieces,2);assert.equal(r.state,'aiming');mass(r);});
test('100 stage configs keep colors, burst amount, gems and target',()=>{for(let stage=1;stage<=100;stage++){const c=S.config(stage,'sand'),r=new P.Run({stage,colors:c.sandColors,burst:c.sandBurst,gems:c.gems});assert.equal(r.colors,stage<=2?2:3);assert.equal(r.burst,c.sandBurst*144);assert.equal(r.field.gems.length,c.gems);assert.ok(c.target>0);}});
test('four-neighbor groups never join across row boundaries',()=>{const f=new M.Field();f.set(119,220,1);f.set(0,221,1);assert.equal(f.groups(2).length,0);});
test('gem remains until a neighboring burst exposes it',()=>{const f=new M.Field();f.addGem(60,235);assert.equal(f.clear([]).gemCount,0);const indices=[];for(let y=231;y<=239;y++)for(let x=55;x<=65;x++)if(!f.cells[y*120+x]){f.set(x,y,1);indices.push(y*120+x);}assert.equal(f.clear([{color:1,indices}]).gemCount,1);});
test('normal rapid play conserves all accepted mass across many bursts',()=>{const r=new P.Run({seed:'play',colors:3});for(let i=0;i<40;i++){r.moveTo([20,60,100][i%3]);r.pour();ticks(r,28);mass(r);if(r.state==='over')break;}settle(r);mass(r);assert.ok(r.accepted>12);});
test('pending input safety bound is explicit and consumes no excess stock',()=>{const r=new P.Run();for(let i=0;i<P.MAX_STREAMS;i++)assert.ok(r.pour());const id=r.active.id;assert.equal(r.pour(),false);assert.equal(r.streams.length,48);assert.equal(r.active.id,id);mass(r);});
test('temporarily occupied active inlet still accepts another click',()=>{const r=new P.Run();r.pour();for(const x of r.columns())r.field.set(x,P.SOURCE_Y,1);assert.ok(r.pour());assert.equal(r.accepted,2);});
console.log('\n'+count+' tests passed.');
